vim.keymap.set("n", "<C-g>l", "gcc", { remap = true, silent = true })
vim.keymap.set("v", "<C-g>l", "gc", { remap = true, silent = true })
vim.keymap.set("n", "<C-g>j", function()
        vim.cmd("normal gcc")
        vim.cmd("normal j")
end, { silent = true })
vim.keymap.set("n", "<C-g>k", function()
        vim.cmd("normal gcc")
        vim.cmd("normal k")
end, { silent = true })
